repos:
  - repo: https://github.com/ambv/black
    rev: stable
    hooks
      - id: black
	language_version: python3.11.5
 - repo: https://github.com/ambv/black
    rev: stable
    hooks
      - id: black
	language_version: python3