# Generated by Django 5.0.4 on 2024-04-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ideas", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="idea",
            name="youtube_url",
            field=models.URLField(null=True),
        ),
    ]
